#define MAX_SEGMENT_SIZE (1<<10)
#define MAX_MAIL_SLOT_SIZE (1<<20)

#define BLOCKING_MODE 0
#define NON_BLOCKING_MODE 1

#define N (1024)

#define CHANGE_WRITE_BLOCKING_MODE_CTL 3
#define CHANGE_READ_BLOCKING_MODE_CTL 4
#define CHANGE_MAX_SEGMENT_SIZE_CTL 5
#define GET_MAX_SEGMENT_SIZE_CTL 6
#define GET_FREESPACE_SIZE_CTL 7
#define GET_WRITE_BLOCKING_MODE_CTL 8
#define GET_READ_BLOCKING_MODE_CTL 9
